"""
report.py
Builds the plain-text detection report that users download after analysis.
"""

from datetime import datetime


def build_text_report(
    file_name: str,
    conf_threshold: float,
    detections: list,
    inference_time_ms: float,
    image_size: tuple,
    model_metrics: dict,
    latitude: str = "",
    longitude: str = "",
    anomaly_count: int = None,
) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    width, height = image_size

    # Optional, manually entered coordinates -- never generated or
    # looked up. If either is blank, show "Location not provided".
    if latitude and str(latitude).strip() and longitude and str(longitude).strip():
        location_str = f"{str(latitude).strip()}, {str(longitude).strip()}"
    else:
        location_str = "Location not provided"

    lines = []
    lines.append("=" * 62)
    lines.append("  DEEPSCAN SONAR -- OBJECT DETECTION REPORT")
    lines.append("=" * 62)
    lines.append(f"Generated:            {ts}")
    lines.append(f"Source image:         {file_name}")
    lines.append(f"Coordinates:          {location_str}")
    lines.append(f"Image dimensions:     {width} x {height} px")
    lines.append(f"Confidence threshold: {conf_threshold:.2f}")
    lines.append(f"Inference time:       {inference_time_ms:.1f} ms")
    lines.append(f"Model:                YOLO11n (custom trained, 4 classes)")
    lines.append("-" * 62)

    if not detections:
        lines.append("No objects detected above the selected confidence threshold.")
    else:
        lines.append(f"Objects detected: {len(detections)}")
        lines.append("")
        lines.append(f"{'#':<4}{'CLASS':<14}{'CONFIDENCE':<14}{'BBOX (x1,y1,x2,y2)'}")
        lines.append("-" * 62)
        for i, det in enumerate(detections, start=1):
            bbox_str = ", ".join(str(v) for v in det["bbox"])
            lines.append(
                f"{i:<4}{det['class'].upper():<14}{det['confidence']*100:>6.1f}%      {bbox_str}"
            )

        lines.append("")
        lines.append("Class summary:")
        counts = {}
        for det in detections:
            counts[det["class"]] = counts.get(det["class"], 0) + 1
        for cls, count in sorted(counts.items(), key=lambda x: -x[1]):
            lines.append(f"  - {cls:<12}: {count}")

    if anomaly_count is not None:
        lines.append("-" * 62)
        lines.append(
            f"Unclassified visual anomalies: {anomaly_count} "
            "(classical CV heuristic, not AI detection)"
        )

    lines.append("-" * 62)
    lines.append("MODEL VALIDATION METRICS (holdout set)")
    lines.append(f"  Precision   : {model_metrics.get('precision', 0):.3f}")
    lines.append(f"  Recall      : {model_metrics.get('recall', 0):.3f}")
    lines.append(f"  mAP50       : {model_metrics.get('map50', 0):.3f}")
    lines.append(f"  mAP50-95    : {model_metrics.get('map50_95', 0):.3f}")
    lines.append(f"  Train images: {model_metrics.get('train_images', 0)}")
    lines.append(f"  Val images  : {model_metrics.get('val_images', 0)}")
    lines.append("=" * 62)
    lines.append("Generated by DeepScan Sonar Intelligence -- for research /")
    lines.append("prototype use. Not certified for navigational safety.")
    lines.append("=" * 62)

    return "\n".join(lines)